name: Build Executables

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build macOS executable
      run: pyinstaller --onefile PyCalc.py
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-executable
        path: dist/PyCalc

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build Linux executable
      run: pyinstaller --onefile PyCalc.py
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: dist/PyCalc
